# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: 'Report Bot'

on:
  workflow_dispatch:
  schedule:
    # 北京时间是 UTC+8 时区，所以如果想在北京时间 00:05 打卡，就需要把定时任务设置在 16:05 (UTC)
    - cron: '20 3 * * *'

jobs:
  submit-report:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm i
    - shell: bash
      env:
        USERNAME: ${{ secrets.USERNAME }}
        PASSWORD: ${{ secrets.PASSWORD }}
        MAIL: ${{ secrets.MAIL }}
        MAIL_HOST: ${{ secrets.MAIL_HOST }}
        MAIL_PORT: ${{ secrets.MAIL_PORT }}
        MAIL_SECURE: ${{ secrets.MAIL_SECURE }}
        MAIL_USER: ${{ secrets.MAIL_USER }}
        MAIL_PASS: ${{ secrets.MAIL_PASS }}
        MAIL_TO: ${{ secrets.MAIL_TO }}
        WECHAT: ${{ secrets.WECHAT }}
        WECHAT_SENDKEY: ${{ secrets.WECHAT_SENDKEY }}
      run: npm start -- -u "$USERNAME" -p "$PASSWORD" -m "$MAIL" -h "$MAIL_HOST" -o "$MAIL_PORT" -s "$MAIL_SECURE" -U "$MAIL_USER" -P "$MAIL_PASS" -t "$MAIL_TO" -w "$WECHAT" -k "$WECHAT_SENDKEY"
